import { Recipe } from "@/types/recipe";

export const DEMO_RECIPES: Recipe[] = [
  {
    id: "demo-1", name: "Classic Sourdough", description: "A crusty, tangy sourdough with an open crumb.",
    ingredients: [
      { id: "i1", name: "Bread flour", amount: "500", unit: "g" },
      { id: "i2", name: "Water", amount: "375", unit: "g" },
      { id: "i3", name: "Sourdough starter", amount: "100", unit: "g" },
      { id: "i4", name: "Salt", amount: "10", unit: "g" },
    ],
    steps: [
      { id: "s1", name: "Autolyse", durationMinutes: 60, instructions: "Mix flour and water, rest covered." },
      { id: "s2", name: "Add starter & salt", durationMinutes: 5, instructions: "Incorporate starter and salt." },
      { id: "s3", name: "Bulk fermentation", durationMinutes: 240, instructions: "Stretch and fold every 30 min." },
      { id: "s4", name: "Shape & cold retard", durationMinutes: 720, instructions: "Shape and refrigerate overnight." },
      { id: "s5", name: "Bake", durationMinutes: 45, instructions: "Bake in Dutch oven at 250°C." },
    ],
    createdAt: "2026-03-01T10:00:00Z", updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "demo-2", name: "Overnight Focaccia", description: "Pillowy, olive-oil-drenched focaccia with crispy edges.",
    ingredients: [
      { id: "i5", name: "All-purpose flour", amount: "500", unit: "g" },
      { id: "i6", name: "Water", amount: "400", unit: "g" },
      { id: "i7", name: "Olive oil", amount: "60", unit: "ml" },
      { id: "i8", name: "Yeast", amount: "3", unit: "g" },
      { id: "i9", name: "Salt", amount: "10", unit: "g" },
    ],
    steps: [
      { id: "s6", name: "Mix", durationMinutes: 10, instructions: "Combine all ingredients." },
      { id: "s7", name: "Overnight rise", durationMinutes: 720, instructions: "Refrigerate 12-18 hours." },
      { id: "s8", name: "Pan & proof", durationMinutes: 120, instructions: "Oil pan, spread dough, proof." },
      { id: "s9", name: "Bake", durationMinutes: 25, instructions: "Bake at 220°C until golden." },
    ],
    createdAt: "2026-03-01T11:00:00Z", updatedAt: "2026-03-01T11:00:00Z",
  },
  {
    id: "demo-3", name: "French Brioche", description: "Rich, buttery brioche with a tender crumb.",
    ingredients: [
      { id: "i10", name: "Bread flour", amount: "500", unit: "g" },
      { id: "i11", name: "Eggs", amount: "5", unit: "large" },
      { id: "i12", name: "Butter", amount: "200", unit: "g" },
      { id: "i13", name: "Sugar", amount: "60", unit: "g" },
      { id: "i14", name: "Yeast", amount: "7", unit: "g" },
    ],
    steps: [
      { id: "s10", name: "Mix & knead", durationMinutes: 20, instructions: "Knead until smooth, add butter gradually." },
      { id: "s11", name: "Bulk rise", durationMinutes: 120, instructions: "Rise until doubled." },
      { id: "s12", name: "Chill", durationMinutes: 480, instructions: "Refrigerate overnight." },
      { id: "s13", name: "Shape & proof", durationMinutes: 90, instructions: "Shape and proof until puffy." },
      { id: "s14", name: "Bake", durationMinutes: 30, instructions: "Egg wash and bake at 180°C." },
    ],
    createdAt: "2026-03-01T12:00:00Z", updatedAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "demo-4", name: "Rye Pumpernickel", description: "Dense, dark pumpernickel with deep malty flavor.",
    ingredients: [
      { id: "i15", name: "Dark rye flour", amount: "400", unit: "g" },
      { id: "i16", name: "Bread flour", amount: "100", unit: "g" },
      { id: "i17", name: "Molasses", amount: "40", unit: "g" },
      { id: "i18", name: "Cocoa powder", amount: "15", unit: "g" },
      { id: "i19", name: "Yeast", amount: "5", unit: "g" },
    ],
    steps: [
      { id: "s15", name: "Mix", durationMinutes: 15, instructions: "Combine all ingredients into a sticky dough." },
      { id: "s16", name: "Bulk rise", durationMinutes: 90, instructions: "Rise in warm spot." },
      { id: "s17", name: "Shape", durationMinutes: 10, instructions: "Shape into loaf pan." },
      { id: "s18", name: "Final proof", durationMinutes: 60, instructions: "Proof until cresting pan." },
      { id: "s19", name: "Low bake", durationMinutes: 120, instructions: "Bake at 150°C for 2 hours." },
    ],
    createdAt: "2026-03-01T13:00:00Z", updatedAt: "2026-03-01T13:00:00Z",
  },
  {
    id: "demo-5", name: "Ciabatta", description: "Airy Italian bread with huge holes and crispy crust.",
    ingredients: [
      { id: "i20", name: "Bread flour", amount: "500", unit: "g" },
      { id: "i21", name: "Water", amount: "400", unit: "g" },
      { id: "i22", name: "Olive oil", amount: "15", unit: "ml" },
      { id: "i23", name: "Yeast", amount: "3", unit: "g" },
      { id: "i24", name: "Salt", amount: "10", unit: "g" },
    ],
    steps: [
      { id: "s20", name: "Mix", durationMinutes: 5, instructions: "Stir into very wet, shaggy dough." },
      { id: "s21", name: "Bulk fermentation", durationMinutes: 180, instructions: "Fold every 30 min for 3 hours." },
      { id: "s22", name: "Divide & shape", durationMinutes: 10, instructions: "Gently divide, minimal handling." },
      { id: "s23", name: "Final proof", durationMinutes: 30, instructions: "Rest on floured couche." },
      { id: "s24", name: "Bake", durationMinutes: 25, instructions: "Bake with steam at 230°C." },
    ],
    createdAt: "2026-03-01T14:00:00Z", updatedAt: "2026-03-01T14:00:00Z",
  },
  {
    id: "demo-6", name: "Pretzel Rolls", description: "Chewy, salty Bavarian-style pretzel rolls with a dark crust.",
    ingredients: [
      { id: "i25", name: "Bread flour", amount: "450", unit: "g" },
      { id: "i26", name: "Water", amount: "280", unit: "ml" },
      { id: "i27", name: "Butter", amount: "30", unit: "g" },
      { id: "i28", name: "Baking soda", amount: "60", unit: "g" },
      { id: "i29", name: "Coarse salt", amount: "10", unit: "g" },
    ],
    steps: [
      { id: "s25", name: "Mix & knead", durationMinutes: 15, instructions: "Knead until smooth and elastic." },
      { id: "s26", name: "Rise", durationMinutes: 60, instructions: "Rise until doubled." },
      { id: "s27", name: "Shape", durationMinutes: 15, instructions: "Divide into 8 rolls." },
      { id: "s28", name: "Lye bath", durationMinutes: 10, instructions: "Dip in baking soda bath, score, salt." },
      { id: "s29", name: "Bake", durationMinutes: 20, instructions: "Bake at 220°C until deep brown." },
    ],
    createdAt: "2026-03-01T15:00:00Z", updatedAt: "2026-03-01T15:00:00Z",
  },
  {
    id: "demo-7", name: "Japanese Milk Bread", description: "Ultra-soft, fluffy shokupan using tangzhong method.",
    ingredients: [
      { id: "i30", name: "Bread flour", amount: "350", unit: "g" },
      { id: "i31", name: "Milk", amount: "200", unit: "ml" },
      { id: "i32", name: "Butter", amount: "40", unit: "g" },
      { id: "i33", name: "Sugar", amount: "40", unit: "g" },
      { id: "i34", name: "Egg", amount: "1", unit: "large" },
    ],
    steps: [
      { id: "s30", name: "Make tangzhong", durationMinutes: 10, instructions: "Cook flour + water roux until thick." },
      { id: "s31", name: "Mix dough", durationMinutes: 20, instructions: "Combine tangzhong with remaining ingredients, knead." },
      { id: "s32", name: "Bulk rise", durationMinutes: 90, instructions: "Rise until doubled." },
      { id: "s33", name: "Shape", durationMinutes: 15, instructions: "Roll and shape into pullman pan." },
      { id: "s34", name: "Final proof", durationMinutes: 60, instructions: "Proof until 1 inch above pan." },
      { id: "s35", name: "Bake", durationMinutes: 35, instructions: "Bake at 175°C with lid on." },
    ],
    createdAt: "2026-03-01T16:00:00Z", updatedAt: "2026-03-01T16:00:00Z",
  },
  {
    id: "demo-8", name: "Pita Bread", description: "Puffy pocket pitas, perfect for stuffing or dipping.",
    ingredients: [
      { id: "i35", name: "All-purpose flour", amount: "300", unit: "g" },
      { id: "i36", name: "Water", amount: "180", unit: "ml" },
      { id: "i37", name: "Olive oil", amount: "15", unit: "ml" },
      { id: "i38", name: "Yeast", amount: "5", unit: "g" },
      { id: "i39", name: "Salt", amount: "5", unit: "g" },
    ],
    steps: [
      { id: "s36", name: "Mix & knead", durationMinutes: 10, instructions: "Knead until smooth." },
      { id: "s37", name: "Rise", durationMinutes: 60, instructions: "Rise until doubled." },
      { id: "s38", name: "Divide & roll", durationMinutes: 15, instructions: "Divide into 8, roll thin rounds." },
      { id: "s39", name: "Rest", durationMinutes: 15, instructions: "Rest rounds covered." },
      { id: "s40", name: "Bake", durationMinutes: 5, instructions: "Bake on hot stone at max temp until puffed." },
    ],
    createdAt: "2026-03-01T17:00:00Z", updatedAt: "2026-03-01T17:00:00Z",
  },
  {
    id: "demo-9", name: "Challah", description: "Beautiful braided egg bread, slightly sweet and golden.",
    ingredients: [
      { id: "i40", name: "Bread flour", amount: "500", unit: "g" },
      { id: "i41", name: "Eggs", amount: "3", unit: "large" },
      { id: "i42", name: "Honey", amount: "80", unit: "g" },
      { id: "i43", name: "Oil", amount: "60", unit: "ml" },
      { id: "i44", name: "Yeast", amount: "7", unit: "g" },
    ],
    steps: [
      { id: "s41", name: "Mix & knead", durationMinutes: 15, instructions: "Knead until windowpane." },
      { id: "s42", name: "Bulk rise", durationMinutes: 90, instructions: "Rise until doubled." },
      { id: "s43", name: "Braid", durationMinutes: 20, instructions: "Divide into strands and braid." },
      { id: "s44", name: "Final proof", durationMinutes: 45, instructions: "Proof until puffy." },
      { id: "s45", name: "Egg wash & bake", durationMinutes: 30, instructions: "Brush and bake at 180°C." },
    ],
    createdAt: "2026-03-01T18:00:00Z", updatedAt: "2026-03-01T18:00:00Z",
  },
  {
    id: "demo-10", name: "Naan Bread", description: "Soft, charred flatbread traditionally cooked in a tandoor.",
    ingredients: [
      { id: "i45", name: "All-purpose flour", amount: "300", unit: "g" },
      { id: "i46", name: "Yogurt", amount: "100", unit: "g" },
      { id: "i47", name: "Milk", amount: "60", unit: "ml" },
      { id: "i48", name: "Ghee", amount: "30", unit: "g" },
      { id: "i49", name: "Yeast", amount: "3", unit: "g" },
    ],
    steps: [
      { id: "s46", name: "Mix & knead", durationMinutes: 10, instructions: "Knead into soft, pliable dough." },
      { id: "s47", name: "Rise", durationMinutes: 60, instructions: "Rise until doubled." },
      { id: "s48", name: "Divide & roll", durationMinutes: 10, instructions: "Divide into 6, roll into teardrops." },
      { id: "s49", name: "Cook", durationMinutes: 15, instructions: "Cook in very hot skillet until charred." },
      { id: "s50", name: "Brush", durationMinutes: 2, instructions: "Brush with melted ghee and garlic." },
    ],
    createdAt: "2026-03-01T19:00:00Z", updatedAt: "2026-03-01T19:00:00Z",
  },
];
